site_name: Prodigy X

theme:
  name: material
  palette:
    scheme: slate
    primary: cyan
  features:
    - toc.follow
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

extra_css:
  - stylesheets/global.css

nav:
  - Prodigy X: index.md
  - Installing: installing.md
  - Creating Bookmarks: creating-bookmarks.md

repo_url: https://github.com/ProdigyAPI/ProdigyX
repo_name: ProdigyAPI/ProdigyX
