site_name: Prodigy X

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate
      primary: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - toc.follow
    - toc.integrate

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list

extra_css:
  - stylesheets/global.css

extra_javascript:
  - javascript/copy-button.js

nav:
  - Prodigy X: index.md
  - Installing: installing.md
  - Creating Bookmarks: creating-bookmarks.md

repo_url: https://github.com/ProdigyAPI/ProdigyX
repo_name: ProdigyAPI/ProdigyX
